export const TEAMS = {
  NBA: [
    {
      fullname: "Atlanta Hawks",
      city: "Atlanta",
      team: "Hawks",
      short: "ATL",
      other: [],
      reddit: "www.reddit.com/r/AtlantaHawks/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
    {
      fullname: "Boston Celtics",
      city: "Boston",
      team: "Celtics",
      short: "BOS",
      other: [],
      reddit: "www.reddit.com/r/bostonceltics/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
    {
      fullname: "Brooklyn Nets",
      city: "Brooklyn",
      team: "Nets",
      short: "BKN",
      other: [],
      reddit: "www.reddit.com/r/GoNets/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
    {
      fullname: "Charlotte Hornets",
      city: "Charlotte",
      team: "Hornets",
      short: "CHA",
      other: [],
      reddit: "www.reddit.com/r/CharlotteHornets/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
    {
      fullname: "Chicago Bulls",
      city: "Chicago",
      team: "Bulls",
      short: "CHI",
      other: [],
      reddit: "www.reddit.com/r/chicagobulls/",
      discord: "https://discord.gg/pCs3uN7GCW",
    },
    {
      fullname: "Cleveland Cavaliers",
      city: "Cleveland",
      team: "Cavaliers",
      short: "CLE",
      other: ["Cavs"],
      reddit: "www.reddit.com/r/clevelandcavs/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
    {
      fullname: "Dallas Mavericks",
      city: "Dallas",
      team: "Mavericks",
      short: "DAL",
      other: ["Mavs"],
      reddit: "www.reddit.com/r/Mavericks/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
    {
      fullname: "Denver Nuggets",
      city: "Denver",
      team: "Nuggets",
      short: "DEN",
      other: [],
      reddit: "www.reddit.com/r/denvernuggets/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
    {
      fullname: "Detroit Pistons",
      city: "Detroit",
      team: "Pistons",
      short: "DET",
      other: [],
      reddit: "www.reddit.com/r/DetroitPistons/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
    {
      fullname: "Golden State Warriors",
      city: "Golden State",
      team: "Warriors",
      short: "GSW",
      other: [],
      reddit: "www.reddit.com/r/warriors/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
    {
      fullname: "Houston Rockets",
      city: "Houston",
      team: "Rockets",
      short: "HOU",
      other: [],
      reddit: "www.reddit.com/r/rockets/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
    {
      fullname: "Indiana Pacers",
      city: "Indiana",
      team: "Pacers",
      short: "IND",
      other: [],
      reddit: "www.reddit.com/r/pacers/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
    {
      fullname: "Los Angeles Clippers",
      city: "Los Angeles",
      team: "Clippers",
      short: "LAC",
      other: ["LA Clippers", "Clips"],
      reddit: "www.reddit.com/r/LAClippers/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
    {
      fullname: "Los Angeles Lakers",
      city: "Los Angeles",
      team: "Lakers",
      short: "LAL",
      other: ["LA Lakers"],
      reddit: "www.reddit.com/r/lakers/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
    {
      fullname: "Memphis Grizzlies",
      city: "Memphis",
      team: "Grizzlies",
      short: "MEM",
      other: [],
      reddit: "www.reddit.com/r/memphisgrizzlies/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
    {
      fullname: "Miami Heat",
      city: "Miami",
      team: "Heat",
      short: "MIA",
      other: [],
      reddit: "www.reddit.com/r/heat/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
    {
      fullname: "Milwaukee Bucks",
      city: "Milwaukee",
      team: "Bucks",
      short: "MIL",
      other: [],
      reddit: "www.reddit.com/r/milwaukeebucks/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
    {
      fullname: "Minnesota Timberwolves",
      city: "Minnesota",
      team: "Timberwolves",
      short: "MIN",
      other: ["Wolves"],
      reddit: "www.reddit.com/r/timberwolves/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
    {
      fullname: "New Orleans Pelicans",
      city: "New Orleans",
      team: "Pelicans",
      short: "NOP",
      other: ["Pels"],
      reddit: "www.reddit.com/r/NOLAPelicans/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
    {
      fullname: "New York Knicks",
      city: "New York",
      team: "Knicks",
      short: "NYK",
      other: ["Knickerbockers"],
      reddit: "www.reddit.com/r/NYKnicks/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
    {
      fullname: "Oklahoma City Thunder",
      city: "Oklahoma City",
      team: "Thunder",
      short: "OKC",
      other: ["OKC"],
      reddit: "www.reddit.com/r/Thunder/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
    {
      fullname: "Orlando Magic",
      city: "Orlando",
      team: "Magic",
      short: "ORL",
      other: [],
      reddit: "www.reddit.com/r/OrlandoMagic/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
    {
      fullname: "Philadelphia Sixers",
      city: "Philadelphia",
      team: "Sixers",
      short: "PHI",
      other: ["76ers"],
      reddit: "www.reddit.com/r/sixers/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
    {
      fullname: "Phoenix Suns",
      city: "Phoenix",
      team: "Suns",
      short: "PHX",
      other: [],
      reddit: "www.reddit.com/r/suns/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
    {
      fullname: "Portland Trail Blazers",
      city: "Portland",
      team: "Trail Blazers",
      short: "POR",
      other: ["Blazers", "Rip City"],
      reddit: "www.reddit.com/r/ripcity/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
    {
      fullname: "Sacramento Kings",
      city: "Sacramento",
      team: "Kings",
      short: "SAC",
      other: [],
      reddit: "www.reddit.com/r/kings/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
    {
      fullname: "San Antonio Spurs",
      city: "San Antonio",
      team: "Spurs",
      short: "SAS",
      other: [],
      reddit: "www.reddit.com/r/NBASpurs/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
    {
      fullname: "Toronto Raptors",
      city: "Toronto",
      team: "Raptors",
      short: "TOR",
      other: [],
      reddit: "www.reddit.com/r/torontoraptors/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
    {
      fullname: "Utah Jazz",
      city: "Utah",
      team: "Jazz",
      short: "UTA",
      other: [],
      reddit: "www.reddit.com/r/UtahJazz/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
    {
      fullname: "Washington Wizards",
      city: "Washington",
      team: "Wizards",
      short: "WAS",
      other: [],
      reddit: "www.reddit.com/r/washingtonwizards/",
      discord: "https://discord.gg/zdhES7dRV2",
    },
  ],
};
